# This is a basic workflow to help you get started with Actions

name: 'to git lab'

on:
  push:
    branches:
      - main

jobs:
  job1:
    name: check repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'show file list'
        run: ls -a
  job2:
    name: upload to gitlab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: i can fly!
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/hishere
          dst: gitlab/Nooneb
          dst_key: ${{secrets.LAB_PRIVATE_KEY}}
          dst_token: ${{secrets.LAB_TOKEN}}
          account_type: user
          clone_style: "https"
          debug: true
          force_update: true
          static_list: "hishere.github.io"
          timeout: '300s'
        
