# This is a basic workflow to help you get started with Actions

name: 'to git lab'

on:
  push:
    branches:
      - main

jobs:
  job1:
    name: job one
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'show file list'
        run: ls
